### BRFSS sex variable analyses

# This script's code uses the GI analytic objects generated by "SOGI_06_GI prepare"
### and produces compares data from sex-at-birth (SAB) module states compare to non-SAB module states in 2019:2021

### Prepare workspace ----- 
# clear environment
rm(list = ls())

# packages
source("SOGI_00_packages.R")

# define functions
tableNA <- function(x, ...){
   table(x, useNA = "ifany", ...)  
}

# call in data
sab_dat <- readRDS("data - clean/brfss_sab.rds")
sab_props_M <- readRDS("data - clean/sab_props_M.rds")
sab_props_F <- readRDS("data - clean/sab_props_F.rds")
sab_comp <- readRDS("data - clean/brfss_sab_compare.rds")
sab_comp_props_M <- readRDS("data - clean/sab_props_M.rds")
sab_comp_props_F <- readRDS("data - clean/sab_props_F.rds")

A_tw <- readRDS("data - clean/sab_bin_props_tw.rds")
A_tm <- readRDS("data - clean/sab_bin_props_tm.rds")
A_nb <- readRDS("data - clean/sab_bin_props_nb.rds")
A_dkns <- readRDS("data - clean/sab_bin_props_dkns.rds")
A_ref <- readRDS("data - clean/sab_bin_props_ref.rds")

B_tw <- readRDS("data - clean/sab_module_props_tw.rds")
B_tm <- readRDS("data - clean/sab_module_props_tm.rds")
B_nb <- readRDS("data - clean/sab_module_props_nb.rds")
B_dkns <- readRDS("data - clean/sab_module_props_dkns.rds")
B_ref <- readRDS("data - clean/sab_module_props_ref.rds")

C_tw <- readRDS("data - clean/sab_comp_props_tw.rds")
C_tm <- readRDS("data - clean/sab_comp_props_tm.rds")
C_nb <- readRDS("data - clean/sab_comp_props_nb.rds")
C_dkns <- readRDS("data - clean/sab_comp_props_dkns.rds")
C_ref <- readRDS("data - clean/sab_comp_props_ref.rds")

# 1: tabulate proportion in each sex group, by gender -----
# Group A: SAB module; SAB variable
round(prop.table(questionr::wtd.table(x=sab_dat$gender,
                                      y=sab_dat$sab,
                                      weights=sab_dat$weight),margin=1)*100,1)

# Group A: SAB module; SAB variable (binary)
round(prop.table(questionr::wtd.table(x=sab_dat$gender,
                                      y=sab_dat$sab_bin,
                                      weights=sab_dat$weight),margin=1)*100,1)

# Group B: SAB module, non-SAB variable
round(prop.table(questionr::wtd.table(x=sab_dat$gender,
                                      y=sab_dat$sex,
                                      weights=sab_dat$weight),margin=1)*100,1)

# Group C: non-SAB module; non-SAB variable
round(prop.table(questionr::wtd.table(x=sab_comp$gender,
                                      y=sab_comp$sex,
                                      weights=sab_comp$weight),margin=1)*100,1)

# 2: plots -----
# generate objects needed for analyses
sex_var_values <- levels(as.factor(sab_comp$sex_bin))

cohort_n <- length(min(sab_comp$cohort):max(sab_comp$cohort))
period_n <- length(min(sab_comp$year):max(sab_comp$year))
cohort_v <- min(sab_comp$cohort):max(sab_comp$cohort) 
period_v <- min(sab_comp$year):max(sab_comp$year)

age_labels <- seq(min(sab_comp$age), max(sab_comp$age), 5)

sab_ids <- c("report being female at birth",
             "report being male at birth")

sex_ids <- c("report being female",
             "report being male")

cols <- rainbow_hcl(cohort_n+1)[1:cohort_n]
cols_pds <- rainbow_hcl(period_n+1)[period_n] 
n_ids <- length(sab_ids)

# * Plots 1: Group A, with binary variable
for (id in 1:n_ids) {
   plot(x= period_v[1] - 
           cohort_v[which(!is.na(gi_props_F[,1,id]))],
        y=gi_props_F[,1,id] %>% na.rm,
        type = "o",
        col = cols_pds[1],
        xlim = c(18, 80),
        ylim = (id==4)*c(94, 100) + (id!=4)*c(0,6),
        xlab = "Respondent age",
        cex.axis = 1.25,
        cex.lab = 1.25,
        cex.main = 1.25,
        ylab = paste0("% of respondents who ", ids[id]),
        main = paste0("Among respondents who report female sex, percent who ", ids[id], ",\n",
                      "by age and organized by period (survey year),", "\n", 
                      "BRFSS (2014-2021)")
   )
   
   temp_x <- period_v[1]-cohort_v[which(!is.na(gi_props_F[,1,id]))]
   temp <- loess((gi_props_F[,1,id] %>% na.rm) ~ temp_x)
   lines(temp$x, temp$fitted, col=cols_pds[1], lwd=3)
   
   for(period in 2:length(period_v)) {
      lines(x= period_v[period] -
               cohort_v[which(!is.na(gi_props_F[,period,id]))],
            y=gi_props_F[,period,id] %>% na.rm,
            type = "o",
            col = cols_pds[period])
      temp_x <- period_v[period]-cohort_v[which(!is.na(gi_props_F[,period,id]))]
      temp <- loess((gi_props_F[,period,id] %>% na.rm) ~ temp_x)
      lines(temp$x, temp$fitted, col=cols_pds[period], lwd=3)
   }
   
   for(cohort in seq(1, length(cohort_v), 5)) {
      legend(c("bottom"[id==4],"topleft"[id!=4]), 
             inset = 0.05, 
             border = "black",
             title = "Period (survey year)",
             legend = c(seq(min(period_v), max(period_v))),
             col = cols_pds[seq(1, length(period_v))],
             lwd = 3,
             lty = 1.5,
             cex = 1,
             ncol = ceiling(length(min(brfss_dat$year):max(brfss_dat$year))/2),
             bg="gray99")
   }
}
