### BRFSS GI Analyses

# This script's code uses the GI analytic objects generated by "SOGI_06_GI prepare"
### and produces results (e.g. plots, statistical analyses)

### Prepare workspace ----- 
# clear environment
rm(list = ls())

# packages
source("SOGI_00_packages.R")

# define functions
tableNA <- function(x, ...){
  table(x, useNA = "ifany", ...)  
}

# call in data
brfss_dat <- readRDS("data - clean/brfss_final.rds")
gi_props_A <- readRDS("data - clean/gi_props_A.rds")
gi_props_F <- readRDS("data - clean/gi_props_F.rds")
gi_props_M <- readRDS("data - clean/gi_props_M.rds")
sab_props_M <- readRDS("data - clean/sab_props_M.rds")
sab_props_F <- readRDS("data - clean/sab_props_F.rds")
sab_dat <- readRDS("data - clean/brfss_sab.rds")

# generate objects needed for analyses
gi_values <- levels(as.factor(brfss_dat$gender))
sex_values <- levels(as.factor(brfss_dat$sex))
cohort_n <- length(min(brfss_dat$cohort):max(brfss_dat$cohort))
period_n <- length(min(brfss_dat$year):max(brfss_dat$year))
cohort_v <- min(brfss_dat$cohort):max(brfss_dat$cohort) 
period_v <- min(brfss_dat$year):max(brfss_dat$year)

# * Plots & Visual Analyses -------
# >> Plots 1: X = reported sex, Y= gender identity ------
ids <- c("Transgender woman", "Transgender man", "Non-binary/Gender non-conforming", 
         "Cisgender", "Don't know/Not sure",
         "Declined to Answer")

cols <- rainbow_hcl(cohort_n) 
cols_pds <- rainbow_hcl(period_n+1)[1:period_n] 
n_ids <- length(ids)

## Core plots: Population = overall, by age organized by survey year ---------
for (id in 1:n_ids) {
  png(filename = paste0("plots/GI_ap_", id, ".png"),
      width = 400, height = 300, units = "px")
  par(mfrow = c(1,1), lend = 1)
  plot(x= rev(period_v[1] - cohort_v),
       y= rev(gi_props_A[,1,id]),
       type = "o",
       col = cols_pds[1],
       xlim = c(18, 80),
       ylim = (id==4)*c(95, 100) + (id!=4)*c(0,3),
       # ylim = c(0, 3),
       xlab = "Age",
       cex.axis = 1,
       cex.lab = 1.25,
       cex.main = 1,
       ylab = paste0("% of respondents"),
       main = paste0(ids[id], "\n", 
                     "BRFSS (2014-2021)")
  )
  
  temp_x <- rev(period_v[1] - cohort_v)
  temp <- loess(rev(gi_props_A[,1,id]) ~ temp_x)
  lines(temp$x, temp$fitted, col=cols_pds[1], lwd=3)
  
  for(period in 2:length(period_v)) {
    lines(x= rev(period_v[period] - cohort_v),
          y= rev(gi_props_A[,period,id]),
          type = "o",
          col = cols_pds[period])
    temp_x <- rev(period_v[period] - cohort_v)
    temp <- loess(rev(gi_props_A[,period,id]) ~ temp_x)
    lines(temp$x, temp$fitted, col=cols_pds[period], lwd=3)
  }
  
  for(cohort in seq(1, length(cohort_v), 5)) {
    legend(c("bottom"[id==4],"topleft"[id!=4]), 
           inset = 0.05, 
           border = "black",
           title = "Period (survey year)",
           legend = c(seq(min(period_v), max(period_v))),
           col = cols_pds[seq(1, length(period_v))],
           lwd = 3,
           lty = 1.5,
           cex = 1,
           # ncol = ceiling(length(min(brfss_dat$year):max(brfss_dat$year))/2),
           ncol = 2,
           bg="gray99",
           bty = "n")
  }
  dev.off()
}

########################################################################################
###### Core plots: 
########################################################################################

### Shared

lwd <- 0.3
cex <- 0.3
loess.lwd <- 1.5
cex.axis <- 0.8
lwd.ticks <- 0.5
cex.axis.labs <- 0.6
cex.main <- 0.8
yline <- 2
xline <- 2
loess.span <- 0.5

### Fig 1: all IDs except cis, by birth cohort, organized by survey year
  
png(filename = paste0("plots/GI_pc_all.png"),
  #  height = 900, width = 1200, units = "px")
  height = 9, width = 6.5, units = "in", res=300)
  par(mfrow = c(3,2), lend = 1)
for (id in c(1:3, 5:6)) {
  id_no <- match(id, c(1:3, 5:6))
  plot(x= cohort_v,
       y= gi_props_A[,1,id],
       type = "o",
       col = cols_pds[1],
       xlim= c(cohort_v[1], cohort_v[cohort_n]),
       ylim = (id==4)*c(95, 100) + (id!=4)*c(0,3),
       #xlab = "Cohort",
       #cex.axis = 1,
       #cex.lab = 1.25,
       #cex.main = 1,
       #ylab = paste0("% of respondents"),
       #main = ""
       cex=cex,
       xlab="", ylab="",
       xaxs="i", yaxs="i",
       axes=FALSE,
       lwd=0.3
  )
  
  temp <- loess(gi_props_A[,1,id] ~ cohort_v, span=loess.span)
  lines(temp$x, temp$fitted, col=cols_pds[1], lwd=loess.lwd)
  
  for(period in 2:length(period_v)) {
    lines(x= cohort_v,
          y= gi_props_A[,period,id],
          type = "o", cex=cex,
          col = cols_pds[period], lwd=lwd)
    temp <- loess(gi_props_A[,period,id] ~ cohort_v, span=loess.span)
    lines(temp$x, temp$fitted, col=cols_pds[period], lwd=loess.lwd)
  }

  axis(1, col = "grey40", col.axis = "grey20", 
       at = seq(1940,2000,10), cex.axis=cex.axis, lwd=0, lwd.ticks=lwd.ticks, mgp=c(3,0.5,0))
  axis(2, col = "grey40", col.axis = "grey20", 
       at = seq(0, 3, 0.25), cex.axis=cex.axis, lwd=0, lwd.ticks=lwd.ticks, mgp=c(3,0.5,0))
  box(col = "grey60")
  mtext("Birth cohort", side = 1, outer = FALSE, cex = cex.axis.labs, line = xline,
        col = "grey20")
  mtext("% of respondents", side = 2, outer = FALSE, cex = cex.axis.labs, 
        line = yline, col = "grey20")
  mtext(paste0(LETTERS[id_no], ") ", ids[id]), side = 3, outer = FALSE, 
        cex = cex.main, col = "grey20", line=0.5, adj=0)

}

plot(NA, xlim = c(0,1),
     ylim = c(0,1), axes = F, xlab = "", ylab = "")
legend(x = "center",inset = 0,
       # inset = 0.05, 
       border = "black",
       title = "Period (survey year)",
       legend = c(seq(min(period_v), max(period_v))),
       col = cols_pds[seq(1, length(period_v))],
       lwd = 2,
       lty = 1.5,
       cex = 1,
       ncol = 2,
       bty = "n",
       bg="gray99")
dev.off()

### Fig S1: all IDs except cis, by age, organized by survey year

png(filename = paste0("plots/GI_ap_all.png"),
    #  height = 900, width = 1200, units = "px")
    height = 9, width = 6.5, units = "in", res=300)
par(mfrow = c(3,2), lend = 1)
for (id in c(1:3, 5:6)) {
  id_no <- match(id, c(1:3, 5:6))
  plot(x= rev(period_v[1] - cohort_v),
       y= rev(gi_props_A[,1,id]),
       type = "o",
       col = cols_pds[1],
       xlim= c(18, 80),
       ylim = (id==4)*c(95, 100) + (id!=4)*c(0,3),
       #xlab = "Age",
       #cex.axis = 1,
       #cex.lab = 1.25,
       #cex.main = 1,
       #ylab = paste0("% of respondents"),
       #main = ""
       cex=cex,
       xlab="", ylab="",
       xaxs="i", yaxs="i",
       axes=FALSE,
       lwd=0.3
  )
  
  temp <- loess(rev(gi_props_A[,1,id]) ~ rev(period_v[1] - cohort_v), span=loess.span)
  lines(temp$x, temp$fitted, col=cols_pds[1], lwd=loess.lwd)
  
  for(period in 2:length(period_v)) {
    lines(x= rev(period_v[period] - cohort_v),
          y= rev(gi_props_A[,period,id]),
          type = "o", cex=cex,
          col = cols_pds[period], lwd=lwd)
    temp <- loess(rev(gi_props_A[,period,id]) ~ 
                    rev(period_v[period] - cohort_v), span=loess.span)
    lines(temp$x, temp$fitted, col=cols_pds[period], lwd=loess.lwd)
    
  }
  axis(1, col = "grey40", col.axis = "grey20", 
       at = seq(20, 80, 5), cex.axis=cex.axis, lwd=0, lwd.ticks=lwd.ticks, mgp=c(3,0.5,0))
  axis(2, col = "grey40", col.axis = "grey20", 
       at = seq(0, 3, 0.25), cex.axis=cex.axis, lwd=0, lwd.ticks=lwd.ticks, mgp=c(3,0.5,0))
  box(col = "grey60")
  mtext("Age", side = 1, outer = FALSE, cex = cex.axis.labs, line = xline,
        col = "grey20")
  mtext("% of respondents", side = 2, outer = FALSE, cex = cex.axis.labs, 
        line = yline, col = "grey20")
  mtext(paste0(LETTERS[id_no], ") ", ids[id]), side = 3, outer = FALSE, 
        cex = cex.main, col = "grey20", line=0.5, adj=0)
}

plot(NA, xlim = c(0,1),
     ylim = c(0,1), axes = F, xlab = "", ylab = "")
legend(x = "center",inset = 0,
       # inset = 0.05, 
       border = "black",
       title = "Period (survey year)",
       legend = c(seq(min(period_v), max(period_v))),
       col = cols_pds[seq(1, length(period_v))],
       lwd = 2,
       lty = 1.5,
       cex = 1,
       ncol = 2,
       bty = "n",
       bg="gray99")
dev.off()


### Fig S2: cis, one panel by cohort and one by age, organized by survey year

lwd <- 0.3
cex <- 0.3
loess.lwd <- 1.5
cex.axis <- 0.5
lwd.ticks <- 0.5
cex.axis.labs <- 0.6
cex.main <- 0.8
yline <- 2
xline <- 2
loess.span <- 0.5

png(filename = paste0("plots/GI_cis.png"),
    #  height = 900, width = 1200, units = "px")
    height = 4, width = 6.5, units = "in", res=300)
par(mfrow = c(1,2), lend = 1)

id <- 4
plot(x= cohort_v,
       y= gi_props_A[,1,id],
       type = "o",
       col = cols_pds[1],
       xlim= c(cohort_v[1], cohort_v[cohort_n]),
       ylim = (id==4)*c(94, 100) + (id!=4)*c(0,3),
       #xlab = "Cohort",
       #cex.axis = 1,
       #cex.lab = 1.25,
       #cex.main = 1,
       #ylab = paste0("% of respondents"),
       #main = ""
       cex=cex,
       xlab="", ylab="",
       xaxs="i", yaxs="i",
       axes=FALSE,
       lwd=0.3
)
  
temp <- loess(gi_props_A[,1,id] ~ cohort_v, span=loess.span)
lines(temp$x, temp$fitted, col=cols_pds[1], lwd=loess.lwd)

for(period in 2:length(period_v)) {
  lines(x= cohort_v,
        y= gi_props_A[,period,id],
        type = "o", cex=cex,
        col = cols_pds[period], lwd=lwd)
  temp <- loess(gi_props_A[,period,id] ~ cohort_v, span=loess.span)
  lines(temp$x, temp$fitted, col=cols_pds[period], lwd=loess.lwd)
}

axis(1, col = "grey40", col.axis = "grey20", 
     at = seq(1940,2000,10), cex.axis=cex.axis, lwd=0, lwd.ticks=lwd.ticks, mgp=c(3,0.5,0))
axis(2, col = "grey40", col.axis = "grey20", 
     at = seq(94, 100, 0.5), cex.axis=cex.axis, lwd=0, lwd.ticks=lwd.ticks, mgp=c(3,0.5,0))
box(col = "grey60")
mtext("Birth cohort", side = 1, outer = FALSE, cex = cex.axis.labs, line = xline,
      col = "grey20")
mtext("% of respondents", side = 2, outer = FALSE, cex = cex.axis.labs, 
      line = yline, col = "grey20")
mtext(paste0(ids[id], ", by cohort"), side = 3, outer = FALSE, 
      cex = cex.main, col = "grey20", line=0.5, adj=0)

legend(x = 1955, #"center",
       y = 95.75,
       border = "black",
       title = "Period (survey year)",
       legend = c(seq(min(period_v), max(period_v))),
       col = cols_pds[seq(1, length(period_v))],
       lwd = 2,
       lty = 1.5,
       cex = 0.5,
       ncol = 2,
       bty = "n",
       bg="gray99")


plot(x= rev(period_v[1] - cohort_v),
     y= rev(gi_props_A[,1,id]),
     type = "o",
     col = cols_pds[1],
     xlim= c(18, 80),
     ylim = (id==4)*c(94, 100) + (id!=4)*c(0,3),
     #xlab = "Age",
     #cex.axis = 1,
     #cex.lab = 1.25,
     #cex.main = 1,
     #ylab = paste0("% of respondents"),
     #main = ""
     cex=cex,
     xlab="", ylab="",
     xaxs="i", yaxs="i",
     axes=FALSE,
     lwd=0.3
)

temp <- loess(rev(gi_props_A[,1,id]) ~ rev(period_v[1] - cohort_v), span=loess.span)
lines(temp$x, temp$fitted, col=cols_pds[1], lwd=loess.lwd)

for(period in 2:length(period_v)) {
  lines(x= rev(period_v[period] - cohort_v),
        y= rev(gi_props_A[,period,id]),
        type = "o", cex=cex,
        col = cols_pds[period], lwd=lwd)
  temp <- loess(rev(gi_props_A[,period,id]) ~ 
                  rev(period_v[period] - cohort_v), span=loess.span)
  lines(temp$x, temp$fitted, col=cols_pds[period], lwd=loess.lwd)
    
}

axis(1, col = "grey40", col.axis = "grey20", 
     at = seq(20, 80, 5), cex.axis=cex.axis, lwd=0, lwd.ticks=lwd.ticks, mgp=c(3,0.5,0))
axis(2, col = "grey40", col.axis = "grey20", 
     at = seq(94, 100, 0.5), cex.axis=cex.axis, lwd=0, lwd.ticks=lwd.ticks, mgp=c(3,0.5,0))
box(col = "grey60")
mtext("Age", side = 1, outer = FALSE, cex = cex.axis.labs, line = xline,
      col = "grey20")
mtext("% of respondents", side = 2, outer = FALSE, cex = cex.axis.labs, 
      line = yline, col = "grey20")
mtext(paste0(ids[id], ", by age"), side = 3, outer = FALSE, 
      cex = cex.main, col = "grey20", line=0.5, adj=0)

dev.off()






##### Vestigial

## Population = female sex, by age organized by survey year
for (id in 1:n_ids) {
  plot(x= period_v[1] - 
         cohort_v[which(!is.na(gi_props_F[,1,id]))],
       y=gi_props_F[,1,id] %>% na.rm,
       type = "o",
       col = cols_pds[1],
       xlim = c(18, 80),
       ylim = (id==4)*c(94, 100) + (id!=4)*c(0,6),
       xlab = "Respondent age",
       cex.axis = 1.25,
       cex.lab = 1.25,
       cex.main = 1.25,
       ylab = paste0("% of respondents who ", ids[id]),
       main = paste0("Among respondents who report female sex, percent who ", ids[id], ",\n",
                     "by age and organized by period (survey year),", "\n", 
                     "BRFSS (2014-2021)")
  )
  
  temp_x <- period_v[1]-cohort_v[which(!is.na(gi_props_F[,1,id]))]
  temp <- loess((gi_props_F[,1,id] %>% na.rm) ~ temp_x)
  lines(temp$x, temp$fitted, col=cols_pds[1], lwd=3)
  
  for(period in 2:length(period_v)) {
    lines(x= period_v[period] -
            cohort_v[which(!is.na(gi_props_F[,period,id]))],
          y=gi_props_F[,period,id] %>% na.rm,
          type = "o",
          col = cols_pds[period])
    temp_x <- period_v[period]-cohort_v[which(!is.na(gi_props_F[,period,id]))]
    temp <- loess((gi_props_F[,period,id] %>% na.rm) ~ temp_x)
    lines(temp$x, temp$fitted, col=cols_pds[period], lwd=3)
  }
  
  for(cohort in seq(1, length(cohort_v), 5)) {
    legend(c("bottom"[id==4],"topleft"[id!=4]), 
           inset = 0.05, 
           border = "black",
           title = "Period (survey year)",
           legend = c(seq(min(period_v), max(period_v))),
           col = cols_pds[seq(1, length(period_v))],
           lwd = 3,
           lty = 1.5,
           cex = 1,
           ncol = ceiling(length(min(brfss_dat$year):max(brfss_dat$year))/2),
           bg="gray99")
  }
}

## Population = female sex, by cohort organized by survey year
for (id in 1:n_ids) {
  plot(x= cohort_v[which(!is.na(gi_props_F[,1,id]))],
       y=gi_props_F[,1,id] %>% na.rm,
       type = "o",
       col = cols_pds[1],
       xlim= c(cohort_v[cohort_n],cohort_v[1]),
       ylim = (id==4)*c(92, 100) + (id!=4)*c(0,8),
       xlab = "Birth cohort",
       cex.axis = 1.25,
       cex.lab = 1.25,
       cex.main = 1.25,
       ylab = paste0("% of respondents who ", ids[id]),
       main = paste0("Among respondents who report female sex, percent who ", ids[id], ",\n",
                     "by birth cohort and organized by period (survey year)", "\n", 
                     "BRFSS (2014-2021)")
  )
  
  temp <- loess((gi_props_F[,1,id] %>% na.rm) ~ 
                  cohort_v[which(!is.na(gi_props_F[,1,id]))])
  lines(temp$x, temp$fitted, col=cols_pds[1], lwd=3)
  
  for(period in 2:length(period_v)) {
    lines(x= cohort_v[which(!is.na(gi_props_F[,period,id]))],
          y=gi_props_F[,period,id] %>% na.rm,
          type = "o",
          col = cols_pds[period])
    temp <- loess((gi_props_F[,period,id] %>% na.rm) ~ 
                    cohort_v[which(!is.na(gi_props_F[,period,id]))])
    lines(temp$x, temp$fitted, col=cols_pds[period], lwd=3)
    
  }
  
  legend(c("bottom"[id==4],"topleft"[id!=4]), 
         inset = 0.05, 
         border = "black",
         title = "Period (survey year)",
         legend = c(seq(min(period_v), max(period_v))),
         col = cols_pds[seq(1, length(period_v))],
         lwd = 3,
         lty = 1.5,
         cex = 1,
         ncol = ceiling(length(min(brfss_dat$year):max(brfss_dat$year))/2),
         bg="gray99")
}

## Population = male sex, by age organized by survey year
for (id in 1:n_ids) {
  plot(x= period_v[1] - 
         cohort_v[which(!is.na(gi_props_M[,1,id]))],
       y=gi_props_M[,1,id] %>% na.rm,
       type = "o",
       col = cols_pds[1],
       xlim = c(19, 80),
       ylim = (id==4)*c(92, 100) + (id!=4)*c(0,8),
       xlab = "Respondent age",
       cex.axis = 1.25,
       cex.lab = 1.25,
       cex.main = 1.25,
       ylab = paste0("% of respondents who ", ids[id]),
       main = paste0("Among respondents who report male sex, percent who ", ids[id], ",\n",
                     "by age and organized by period (survey year),", "\n", 
                     "BRFSS (2014-2021)")
  )
  
  temp_x <- period_v[1]-cohort_v[which(!is.na(gi_props_M[,1,id]))]
  temp <- loess((gi_props_M[,1,id] %>% na.rm) ~ temp_x)
  lines(temp$x, temp$fitted, col=cols_pds[1], lwd=3)
  
  for(period in 2:length(period_v)) {
    lines(x= period_v[period] -
            cohort_v[which(!is.na(gi_props_M[,period,id]))],
          y=gi_props_M[,period,id] %>% na.rm,
          type = "o",
          col = cols_pds[period])
    temp_x <- period_v[period]-cohort_v[which(!is.na(gi_props_M[,period,id]))]
    temp <- loess((gi_props_M[,period,id] %>% na.rm) ~ temp_x)
    lines(temp$x, temp$fitted, col=cols_pds[period], lwd=3)
  }
  
  for(cohort in seq(1, length(cohort_v), 5)) {
    legend(c("bottom"[id==4],"topleft"[id!=4]), 
           inset = 0.05, 
           border = "black",
           title = "Period (survey year)",
           legend = c(seq(min(period_v), max(period_v))),
           col = cols_pds[seq(1, length(period_v))],
           lwd = 3,
           lty = 1.5,
           cex = 1,
           ncol = ceiling(length(min(brfss_dat$year):max(brfss_dat$year))/2),
           bg="gray99")
  }
}

## Population = male sex, by cohort organized by survey year
for (id in 1:n_ids) {
  plot(x= cohort_v[which(!is.na(gi_props_M[,1,id]))],
       y=gi_props_M[,1,id] %>% na.rm,
       type = "o",
       col = cols_pds[1],
       xlim= c(cohort_v[cohort_n],cohort_v[1]),
       ylim = (id==4)*c(94, 100) + (id!=4)*c(0,6),
       xlab = "Birth cohort",
       cex.axis = 1.25,
       cex.lab = 1.25,
       cex.main = 1.25,
       ylab = paste0("% of respondents who ", ids[id]),
       main = paste0("Among respondents who report male sex, percent who ", ids[id], ",\n",
                     "by birth cohort and organized by period (survey year)", "\n", 
                     "BRFSS (2014-2021)")
  )
  
  temp <- loess((gi_props_M[,1,id] %>% na.rm) ~ 
                  cohort_v[which(!is.na(gi_props_M[,1,id]))])
  lines(temp$x, temp$fitted, col=cols_pds[1], lwd=3)
  
  for(period in 2:length(period_v)) {
    lines(x= cohort_v[which(!is.na(gi_props_M[,period,id]))],
          y=gi_props_M[,period,id] %>% na.rm,
          type = "o",
          col = cols_pds[period])
    temp <- loess((gi_props_M[,period,id] %>% na.rm) ~ 
                    cohort_v[which(!is.na(gi_props_M[,period,id]))])
    lines(temp$x, temp$fitted, col=cols_pds[period], lwd=3)
    
  }
  
  legend(c("bottom"[id==4],"topleft"[id!=4]), 
         inset = 0.05, 
         border = "black",
         title = "Period (survey year)",
         legend = c(seq(min(period_v), max(period_v))),
         col = cols_pds[seq(1, length(period_v))],
         lwd = 3,
         lty = 1.5,
         cex = 1,
         ncol = ceiling(length(min(brfss_dat$year):max(brfss_dat$year))/2),
         bg="gray99")
}

### >> Plots 2: X = gender identity, Y = sex at birth ------
# prepare plotting objects 
cohort_n_sab <- length(min(sab_dat$cohort):max(sab_dat$cohort))
period_n_sab <- length(min(sab_dat$year):max(sab_dat$year))
cohort_v_sab <- min(sab_dat$cohort):max(sab_dat$cohort) 
period_v_sab <- min(sab_dat$year):max(sab_dat$year)

ids_sab <- c("assigned male at birth", "assigned female at birth", "did not know their SAB", "did not disclose their SAB")
cols_sab <- rainbow_hcl(cohort_n_sab) 
cols_pds_sab <- rainbow_hcl(period_n_sab) 

ids_sab <- sort(unique(sab_dat$sab))
n_ids_sab <- length(ids_sab)

## >> * Population = female SAB, by cohort organized by survey year ------
for (id in 1:n_ids) {
  plot(x= cohort_v_sab[which(!is.na(sab_props_F[,1,id]))],
       y=sab_props_F[,1,id] %>% na.rm,
       type = "o",
       col = cols_pds_sab[1],
       xlim= c(cohort_v_sab[cohort_n_sab],cohort_v_sab[1]),
       ylim = (id!=4)*c(0,20) + (id == 4)*c(90,100),
       xlab = "Birth cohort",
       cex.axis = 1.25,
       cex.lab = 1.25,
       cex.main = 1.25,
       ylab = paste0("% of respondents who ", ids[id]),
       main = paste0("Among respondents who were assigned female sex at birth,", "\n", "percent who ", ids[id], ",\n",
                     "by birth cohort and organized by period (survey year), BRFSS (2019-2021)")
  )
  
  temp <- loess((sab_props_F[,1,id] %>% na.rm) ~ 
                  cohort_v_sab[which(!is.na(sab_props_F[,1,id]))])
  lines(temp$x, temp$fitted, col=cols_pds_sab[1], lwd=3)
  
  for(period in 2:length(period_v_sab)) {
    lines(x= cohort_v_sab[which(!is.na(sab_props_F[,period,id]))],
          y=sab_props_F[,period,id] %>% na.rm,
          type = "o",
          col = cols_pds_sab[period])
    temp <- loess((gi_props_M[,period,id] %>% na.rm) ~ 
                    cohort_v_sab[which(!is.na(sab_props_F[,period,id]))])
    lines(temp$x, temp$fitted, col=cols_pds_sab[period], lwd=3)
    
  }
  
  legend(c("bottomleft"[id==4],"topleft"[id!=4]), 
         inset = 0.05, 
         border = "black",
         title = "Period (survey year)",
         legend = c(seq(min(period_v_sab), max(period_v_sab))),
         col = cols_pds_sab[seq(1, length(period_v_sab))],
         lwd = 3,
         lty = 1.5,
         cex = 1,
         bg="gray99")
}

## >> * Population = female SAB, by age organized by survey year ------
for (id in 1:n_ids) {
  plot(x= period_v_sab[1] - 
         cohort_v_sab[which(!is.na(sab_props_F[,1,id]))],
       y=sab_props_F[,1,id] %>% na.rm,
       type = "o",
       col = cols_pds_sab[1],
       xlim = c(18, 80),
       ylim = (id==4)*c(90, 100) + (id!=4)*c(0,15),
       xlab = "Respondent age",
       cex.axis = 1.25,
       cex.lab = 1.25,
       cex.main = 1.25,
       ylab = paste0("% of respondents who ", ids[id]),
       main = paste0("Among respondents who were assigned female sex at birth,", "\n", "percent who ", ids[id], ",\n",
                     "by age and organized by period (survey year), BRFSS (2019-2021)")
  )
  
  temp_x <- period_v_sab[1]-cohort_v_sab[which(!is.na(sab_props_F[,1,id]))]
  temp <- loess((sab_props_F[,1,id] %>% na.rm) ~ temp_x)
  lines(temp$x, temp$fitted, col=cols_pds_sab[1], lwd=3)
  
  for(period in 2:length(period_v_sab)) {
    lines(x= period_v_sab[period] -
            cohort_v_sab[which(!is.na(sab_props_F[,period,id]))],
          y=sab_props_F[,period,id] %>% na.rm,
          type = "o",
          col = cols_pds_sab[period])
    temp_x <- period_v_sab[period]-cohort_v_sab[which(!is.na(sab_props_F[,period,id]))]
    temp <- loess((sab_props_F[,period,id] %>% na.rm) ~ temp_x)
    lines(temp$x, temp$fitted, col=cols_pds_sab[period], lwd=3)
  }
  
  for(cohort in seq(1, length(cohort_v_sab), 5)) {
    legend(c("bottomleft"[id==4],"topleft"[id!=4]), 
           inset = 0.05, 
           border = "black",
           title = "Period (survey year)",
           legend = c(seq(min(period_v_sab), max(period_v_sab))),
           col = cols_pds_sab[seq(1, length(period_v_sab))],
           lwd = 3,
           lty = 1.5,
           cex = 1,
           bg="gray99")
  }
}


## >> * Population = male SAB, by cohort organized by survey year ------
for (id in 1:n_ids) {
  plot(x= cohort_v_sab[which(!is.na(sab_props_M[,1,id]))],
       y=sab_props_M[,1,id] %>% na.rm,
       type = "o",
       col = cols_pds_sab[1],
       xlim= c(cohort_v_sab[cohort_n_sab],cohort_v_sab[1]),
       ylim = (id!=4)*c(0,20) + (id == 4)*c(90,100),
       xlab = "Birth cohort",
       cex.axis = 1.25,
       cex.lab = 1.25,
       cex.main = 1.25,
       ylab = paste0("% of respondents who ", ids[id]),
       main = paste0("Among respondents who were assigned male sex at birth,", "\n", "percent who ", ids[id], ",\n",
                     "by birth cohort and organized by period (survey year), BRFSS (2019-2021)")
  )
  
  temp <- loess((sab_props_M[,1,id] %>% na.rm) ~ 
                  cohort_v_sab[which(!is.na(sab_props_M[,1,id]))])
  lines(temp$x, temp$fitted, col=cols_pds_sab[1], lwd=3)
  
  for(period in 2:length(period_v_sab)) {
    lines(x= cohort_v_sab[which(!is.na(sab_props_M[,period,id]))],
          y=sab_props_M[,period,id] %>% na.rm,
          type = "o",
          col = cols_pds_sab[period])
    temp <- loess((gi_props_M[,period,id] %>% na.rm) ~ 
                    cohort_v_sab[which(!is.na(sab_props_M[,period,id]))])
    lines(temp$x, temp$fitted, col=cols_pds_sab[period], lwd=3)
    
  }
  
  legend(c("bottomleft"[id==4],"topleft"[id!=4]), 
         inset = 0.05, 
         border = "black",
         title = "Period (survey year)",
         legend = c(seq(min(period_v_sab), max(period_v_sab))),
         col = cols_pds_sab[seq(1, length(period_v_sab))],
         lwd = 3,
         lty = 1.5,
         cex = 1,
         bg="gray99")
}


## >> * Population = male SAB, by age organized by survey year ------
for (id in 1:n_ids) {
  plot(x= period_v_sab[1] - 
         cohort_v_sab[which(!is.na(sab_props_M[,1,id]))],
       y=sab_props_M[,1,id] %>% na.rm,
       type = "o",
       col = cols_pds_sab[1],
       xlim = c(18, 80),
       ylim = (id==4)*c(90, 100) + (id!=4)*c(0,15),
       xlab = "Respondent age",
       cex.axis = 1.25,
       cex.lab = 1.25,
       cex.main = 1.25,
       ylab = paste0("% of respondents who ", ids[id]),
       main = paste0("Among respondents who were assigned male sex at birth,", "\n", "percent who ", ids[id], ",\n",
                     "by age and organized by period (survey year), BRFSS (2019-2021)")
  )
  
  temp_x <- period_v_sab[1]-cohort_v_sab[which(!is.na(sab_props_M[,1,id]))]
  temp <- loess((sab_props_M[,1,id] %>% na.rm) ~ temp_x)
  lines(temp$x, temp$fitted, col=cols_pds_sab[1], lwd=3)
  
  for(period in 2:length(period_v_sab)) {
    lines(x= period_v_sab[period] -
            cohort_v_sab[which(!is.na(sab_props_M[,period,id]))],
          y=sab_props_M[,period,id] %>% na.rm,
          type = "o",
          col = cols_pds_sab[period])
    temp_x <- period_v_sab[period]-cohort_v_sab[which(!is.na(sab_props_M[,period,id]))]
    temp <- loess((sab_props_M[,period,id] %>% na.rm) ~ temp_x)
    lines(temp$x, temp$fitted, col=cols_pds_sab[period], lwd=3)
  }
  
  for(cohort in seq(1, length(cohort_v_sab), 5)) {
    legend(c("bottomleft"[id==4],"topleft"[id!=4]), 
           inset = 0.05, 
           border = "black",
           title = "Period (survey year)",
           legend = c(seq(min(period_v_sab), max(period_v_sab))),
           col = cols_pds_sab[seq(1, length(period_v_sab))],
           lwd = 3,
           lty = 1.5,
           cex = 1,
           bg="gray99")
  }
}


# * Descriptive Analyses ------
# * * subset by gender identity
tw <- subset(brfss_dat, gender == "1_transwoman")
tm <- subset(brfss_dat, gender == "2_transman")
nb <- subset(brfss_dat, gender == "3_nbgnc")

str <- subset(brfss_dat, so_new == "1_straight")
lg <- subset(brfss_dat, so_new == "2_lesgay")
bi <- subset(brfss_dat, so_new == "3_bi")
dko <- subset(brfss_dat, so_new == "4_dko")
ref <- subset(brfss_dat, so_new == "5_ref")

tw_str <- subset(tw, so_new == "1_straight")
tw_lg <- subset(tw, so_new == "2_lesgay")
tw_bi <- subset(tw, so_new == "3_bi")
tw_dko <- subset(tw, so_new == "4_dko")
tw_ref <- subset(tw, so_new == "5_ref")

tm_str <- subset(tm, so_new == "1_straight")
tm_lg <- subset(tm, so_new == "2_lesgay")
tm_bi <- subset(tm, so_new == "3_bi")
tm_dko <- subset(tm, so_new == "4_dko")
tm_ref <- subset(tm, so_new == "5_ref")

nb_str <- subset(nb, so_new == "1_straight")
nb_lg <- subset(nb, so_new == "2_lesgay")
nb_bi <- subset(nb, so_new == "3_bi")
nb_dko <- subset(nb, so_new == "4_dko")
nb_ref <- subset(nb, so_new == "5_ref")

# * * How does is self-described sex distributed among respondents who identify as transgender? -----
round(prop.table(questionr::wtd.table(x= tw$year, y= tw$sex, weights = tw$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= tm$year, y= tm$sex, weights = tm$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= nb$year, y= nb$sex, weights = nb$weight),margin=1)*100,1)

# * * ... by SO? -----
# * * * trans women
round(prop.table(questionr::wtd.table(x= tw_str$year, y= tw_str$sex, weights = tw_str$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= tw_lg$year, y= tw_lg$sex, weights = tw_lg$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= tw_bi$year, y= tw_bi$sex, weights = tw_bi$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= tw_dko$year, y= tw_dko$sex, weights = tw_dko$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= tw_ref$year, y= tw_ref$sex, weights = tw_ref$weight),margin=1)*100,1)

# * * * trans men
round(prop.table(questionr::wtd.table(x= tm_str$year, y= tm_str$sex, weights = tm_str$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= tm_lg$year, y= tm_lg$sex, weights = tm_lg$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= tm_bi$year, y= tm_bi$sex, weights = tm_bi$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= tm_dko$year, y= tm_dko$sex, weights = tm_dko$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= tm_ref$year, y= tm_ref$sex, weights = tm_ref$weight),margin=1)*100,1)

# * * * nonbinary
round(prop.table(questionr::wtd.table(x= nb_str$year, y= nb_str$sex, weights = nb_str$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= nb_lg$year, y= nb_lg$sex, weights = nb_lg$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= nb_bi$year, y= nb_bi$sex, weights = nb_bi$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= nb_dko$year, y= nb_dko$sex, weights = nb_dko$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= nb_ref$year, y= nb_ref$sex, weights = nb_ref$weight),margin=1)*100,1)


# * * How does gender identity and SO interact? -----
round(prop.table(questionr::wtd.table(x= tw$year, y= tw$so_new, weights = tw$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= tm$year, y= tm$so_new, weights = tm$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= nb$year, y= nb$so_new, weights = nb$weight),margin=1)*100,1)

# * * How does gender identity break down by SO? -----
round(prop.table(questionr::wtd.table(x= str$year, y= str$gender, weights = str$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= lg$year, y= lg$gender, weights = lg$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= bi$year, y= bi$gender, weights = bi$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= dko$year, y= dko$gender, weights = dko$weight),margin=1)*100,1)
round(prop.table(questionr::wtd.table(x= ref$year, y= ref$gender, weights = ref$weight),margin=1)*100,1)

# * Sex-at-birth variable & gender identity --------
round(prop.table(tableNA(sab_dat$gender, sab_dat$sab),margin=1)*100,1)
round(prop.table(tableNA(sab_dat$sab, sab_dat$sex),margin=1)*100,1)

round(prop.table(questionr::wtd.table(x= sab_dat$gender, y= sab_dat$sab, weights = sab_dat$weight),margin=1)*100,1)
